lab 1
alvls/mp1-2023-1 pull request #10
Opened 2023-03-01 15:20 UTC by Gn4ik

2023-03-13 13:48 UTC, alvls requested changes

2023-03-13 13:48 UTC, alvls commented on gnitienko_ky/task1/Source.cpp
> +		cout << "����: ";
Вся работа с консолью, кроме печати, должна располагаться вне класса, например, в функции main. Все необходимые параметры должны поступать в методы класса через аргументы. Нужно переделать.

2023-03-14 11:27 UTC, alvls commented
Кирилл, попробую пояснить еще раз. Ваш текущий вариант класса подразумевает, что его можно использовать только с консолью ввода/вывода, поскольку прямо в методах класса происходит ввод и вывод данных. Получается, что класс нельзя использовать в программах, где консоли нет (системных или с графическим интерфейсом).
Переделайте методы так, чтобы данные поступали в методы через параметры, а результаты возвращались из методов.

2023-03-14 13:42 UTC, alvls requested changes

2023-03-14 13:42 UTC, alvls commented on gnitienko_ky/task1/Source.cpp
> +	void Difference() {
Разница времен - это тоже время, так что его нужно не печатать, а вернуть, как объект класса Time.

2023-03-14 15:48 UTC, alvls commented
А теперь исправили лишнего. Верните методы печати. И сделайте один метод Difference, который возвращает объект класса Time.

2023-03-16 12:00 UTC, Gn4ik commented
Метод Difference не выводит на консоль значения полей новой переменной

2023-03-16 12:19 UTC, alvls commented
Теперь похоже на то, что нужно. Считаете разницу вы, правда, неверно, но на этот раз засчитаю.

| __Работа  принята__       |      |
| ------------------------- | ---- |
| __Ваш текущий балл:__     |      |
| Функциональность:         | 2,9  |
| Качество  проектирования: | 1,5  |
| Качество кода:            | 1,3  |
| Бонус:                    | 0,0  |
| Штраф:                    | 0,0  |
| __Итого:__                | 5,7  |

2023-03-20 14:56 UTC, alvls commented
Кирилл, внести в код второго задания исправления в соответствие с тем, что я писал выше и тем, что мы обсуждали на практике.

2023-03-20 15:45 UTC, Gn4ik commented
В методе сложения двух матриц тоже нужно, чтобы он возвращал значение?

2023-03-20 16:18 UTC, alvls commented
> В методе сложения двух матриц тоже нужно, чтобы он возвращал значение?

Да.

2023-03-20 17:41 UTC, Gn4ik commented
А почему чтение памяти матриц 2 и 3 в методах невозможно? они же являются полями

2023-03-20 17:53 UTC, alvls commented
> А почему чтение памяти матриц 2 и 3 в методах невозможно? они же являются полями

Не понял вопрос. Кроме того, в классе нет смысла выделять память под 3 матрицы - нужна только одна.

2023-03-23 12:37 UTC, alvls requested changes

2023-03-23 12:37 UTC, alvls commented on gnitienko_ky/task2/Source.cpp
> +	}
Эти два метода нужно убрать из класса

2023-03-23 12:48 UTC, Gn4ik commented on gnitienko_ky/task2/Source.cpp
> +	}
Но с помощью этих методов происходит заполнение матриц. Если их убрать, то матрицы будут пустыми.

2023-03-23 13:20 UTC, alvls commented on gnitienko_ky/task2/Source.cpp
> +	}
Заполнять матрицы нужно вне класса, например, в main

2023-03-23 14:00 UTC, alvls commented
Кирилл, на этот раз я снижать не стал. Дальше постарайтесь сразу учесть замечания, которые были по первым двум заданиям.

| __Работа  принята__       |      |
| ------------------------- | ---- |
| __Ваш текущий балл:__     |      |
| Функциональность:         | 3,0  |
| Качество  проектирования: | 1,5  |
| Качество кода:            | 1,5  |
| Бонус:                    | 0,0  |
| Штраф:                    | 0,0  |
| __Итого:__                | 6,0  |

2023-03-28 08:44 UTC, alvls commented
По заданию 3

Не выполнено требование "В минимальном варианте длина последовательности не должна превышать длину поля ввода". В остальном годится.

| __Работа  принята__       |      |
| ------------------------- | ---- |
| __Ваш текущий балл:__     |      |
| Функциональность:         | 3,6  |
| Качество  проектирования: | 2,0  |
| Качество кода:            | 2,0  |
| Бонус:                    | 0,0  |
| Штраф:                    | 0,0  |
| __Итого:__                | 7,6  |

2023-03-30 12:05 UTC, merged