Task 1
alvls/mp1-2023-1 pull request #11
Opened 2023-03-01 16:12 UTC by hasanyanovk

Здравствуйте, сделал задание с учётом того, что система поддерживает 64-битные числа, так как в противном случае работать не будет. Надеюсь, что правильно понял задание

2023-03-01 18:02 UTC, hasanyanovk commented
А так же я сделал вывод внутри класса, что нелогично, но вроде как соответствует тз
(хотя я думаю, что лучше было бы вынести его как обычную ф-ю

2023-03-14 10:23 UTC, alvls commented
Кирилл, по заданию 1 - отличная реализация!

| __Работа  принята__       |      |
| ------------------------- | ---- |
| __Ваш текущий балл:__     |      |
| Функциональность:         | 3,0  |
| Качество  проектирования: | 1,5  |
| Качество кода:            | 1,5  |
| Бонус:                    | 0,5  |
| Штраф:                    | 0,0  |
| __Итого:__                | 6,5  |

2023-03-19 14:27 UTC, hasanyanovk commented
Здравствуйте, у меня возникло несколько вопросов в ходе выполнения 3 задания.
1) Возможно я не правильно понял, что значит "вывести меню в выбранной позиции окна консоли"
2) По-моему, немного нелогично, что класс своими методами что то выводит в консоль, но я так понял, что это специфика конкретно этого задания.
Ну в любом случае, если что, переделаю

2023-03-19 17:12 UTC, alvls commented
> Здравствуйте, у меня возникло несколько вопросов в ходе выполнения 3 задания.
> 
>     1. Возможно я не правильно понял, что значит "вывести меню в выбранной позиции окна консоли"
> 
>     2. По-моему, немного нелогично, что класс своими методами что то выводит в консоль, но я так понял, что это специфика конкретно этого задания.
>        Ну в любом случае, если что, переделаю

Все верно - это специфика данного задания. Вывод меню на экран входит в задачи данного класса

2023-03-20 15:09 UTC, alvls requested changes

2023-03-20 15:09 UTC, alvls commented on khasanyanov_kv/task2/Source.cpp
> +	}
Не нужно ничего выводить на экран в методах класса

2023-03-20 15:09 UTC, alvls commented on khasanyanov_kv/task2/Source.cpp
> +		arr = new int[size];
Новуя память выделили, а старую потеряли...

2023-03-20 15:09 UTC, alvls commented on khasanyanov_kv/task2/Source.cpp
> +	static vec sum_of_vectors(vec a, vec b)
1. static не нужен
2. переделайте метод, исходя из обсуждения на последней практике

2023-03-20 15:09 UTC, alvls commented on khasanyanov_kv/task2/Source.cpp
> +	int composition_with(vec a)
1. Исправьте название
2. Параметр лучше принимать по конст ссылке

2023-03-20 16:47 UTC, hasanyanovk commented
Здравствуйте, реализовал немного по-другому все, подумал, что так будет функциональнее.
Решил избавиться от set_size.
Вроде все исправил

2023-03-20 18:04 UTC, alvls commented
| __Работа  принята__       |      |
| ------------------------- | ---- |
| __Ваш текущий балл:__     |      |
| Функциональность:         | 3,0  |
| Качество  проектирования: | 1,5  |
| Качество кода:            | 1,5  |
| Бонус:                    | 0,1  |
| Штраф:                    | 0,0  |
| __Итого:__                | 6,1  |

2023-03-28 09:04 UTC, alvls requested changes

2023-03-28 09:04 UTC, alvls commented on khasanyanov_kv/task3/Source.cpp
> +	Menu(Menu& other)
Добавьте const

2023-03-28 09:04 UTC, alvls commented on khasanyanov_kv/task3/Source.cpp
> +	void set_size(int Size) { size = Size; }
Поменяв размер вы не перевыделили память

2023-03-28 10:34 UTC, hasanyanovk commented on khasanyanov_kv/task3/Source.cpp
> +	void set_size(int Size) { size = Size; }
Здравствуйте, переделал.

2023-03-28 10:51 UTC, alvls requested changes

2023-03-28 10:51 UTC, alvls commented on khasanyanov_kv/task3/Source.cpp
> +	void set_size(int Size)
Код метода написан а) неверно, б) неоптимально. Нужно всего одно новое выделение памяти в каждой из веток. И нужно не забыть про удаление старой памяти.

2023-03-28 12:09 UTC, khasanyanovk commented on khasanyanov_kv/task3/Source.cpp
> +	void set_size(int Size)
Я, честно говоря, не понимаю, как это нужно сделать и как не потерять старые значения пунктов меню

2023-03-28 12:22 UTC, alvls commented on khasanyanov_kv/task3/Source.cpp
> +	void set_size(int Size)
Выделяете память под новый размер. Копируете данные из старой памяти. Удаляете старую память. Переназначаете указатель.

2023-03-28 12:42 UTC, hasanyanovk commented on khasanyanov_kv/task3/Source.cpp
> +	void set_size(int Size)
Не уверен, что правильно сделал, но все же

2023-03-28 12:46 UTC, alvls commented on khasanyanov_kv/task3/Source.cpp
> +	void set_size(int Size)
Теперь верно

2023-03-28 12:46 UTC, alvls commented
| __Работа  принята__       |      |
| ------------------------- | ---- |
| __Ваш текущий балл:__     |      |
| Функциональность:         | 4,0  |
| Качество  проектирования: | 2,0  |
| Качество кода:            | 2,0  |
| Бонус:                    | 0,0  |
| Штраф:                    | 0,0  |
| __Итого:__                | 8,0  |

2023-04-07 06:50 UTC, alvls commented
По заданию 4 все хорошо. Замечаний нет.

| __Работа принята__        |      |
| ------------------------- | ---- |
| __Ваш текущий  балл:__    |      |
| Функциональность:         | 4,0  |
| Качество  проектирования: | 2,0  |
| Качество  кода:           | 2,0  |
| Бонус:                    | 0,0  |
| Штраф:                    | 0,0  |
| __Итого:__                | 8,0  |

2023-04-07 06:50 UTC, merged