task 1 completed
alvls/mp1-2023-1 pull request #12
Opened 2023-03-01 16:48 UTC by belovtut

2023-03-13 13:07 UTC, alvls requested changes

2023-03-13 13:07 UTC, alvls commented on belov_aa/task1/source.cpp
> +    void add(int numerator, int denominator)
Параметром в методах, реализующих операции, должно выступать другое рациональное число, а не отдельно числитель и знаменатель.

2023-03-13 13:07 UTC, alvls commented on belov_aa/task1/source.cpp
> +        }
На этот раз можете не исправлять. На будущее - в конструкторе не должно быть работы с консолью.

В данной задаче пользователь класса должен позаботиться, чтобы параметры были верными (по условию).

2023-03-13 15:13 UTC, belovtut commented
@alvls исправлено :)

2023-03-13 17:56 UTC, alvls commented on belov_aa/task1/source.cpp
> +        if (fraction.denominator == 0)
Это условие сработает хоть когда-нибудь?

2023-03-13 17:56 UTC, alvls commented on belov_aa/task1/source.cpp
> +        if (fraction.numerator * fraction.denominator == 0) // ���� ���� �� ���� �� ���� ���������� = 0, �� � �� ������������ = 0
Это условие сработает хоть когда-нибудь?

2023-03-13 19:43 UTC, belovtut commented
Ранее были необходимы эти проверки для числителя и знаменателя, поскольку в качестве параметра передавался не объект класса, а непосредственно два значения для них. В операции деления оставил проверку на нуль в числителе дроби-делителя, т.к. в противном случае рискую получить 0 в знаменателе дроби-результата.

2023-03-13 20:48 UTC, alvls commented
Убедили.
По заданию 1.

| __Работа  принята__       |      |
| ------------------------- | ---- |
| __Ваш текущий балл:__     |      |
| Функциональность:         | 3,0  |
| Качество  проектирования: | 1,5  |
| Качество кода:            | 1,5  |
| Бонус:                    | 0,2  |
| Штраф:                    | 0,0  |
| __Итого:__                | 6,2  |

2023-03-20 15:14 UTC, alvls commented
По заданию 2 все хорошо.

| __Работа  принята__       |      |
| ------------------------- | ---- |
| __Ваш текущий балл:__     |      |
| Функциональность:         | 3,0  |
| Качество  проектирования: | 1,5  |
| Качество кода:            | 1,5  |
| Бонус:                    | 0,2  |
| Штраф:                    | 0,0  |
| __Итого:__                | 6,2  |

2023-03-20 15:15 UTC, merged