task1
alvls/mp1-2023-1 pull request #14
Opened 2023-03-01 19:09 UTC by ermilovad

2023-03-14 11:08 UTC, alvls requested changes

2023-03-14 11:08 UTC, alvls commented on Ermilova_DS/task1/ConsoleApplication.cpp
> +	string name;
Данные не должны находиться в public-секции класса

2023-03-14 11:08 UTC, alvls commented on Ermilova_DS/task1/ConsoleApplication.cpp
> +	double Getcnt(double coefficient)
Неудачное название. Впрочем, этот метод нужно вообще удалить. А вместо него реализовать несколько методов, конвертирующих длину в метрах в другие единицы. Сейчас у вас это делается в основной программе, а должно в методах класса.

При этом обратите внимание, чтобы данные поступали в методы через параметры, а результаты возвращались из методов. Вывод на консоль должен быть в одном методе класса, как и сказано в задании.

2023-03-16 12:21 UTC, alvls commented
| __Работа  принята__       |      |
| ------------------------- | ---- |
| __Ваш текущий балл:__     |      |
| Функциональность:         | 3,0  |
| Качество  проектирования: | 1,5  |
| Качество кода:            | 1,5  |
| Бонус:                    | 0,0  |
| Штраф:                    | 0,0  |
| __Итого:__                | 6,0  |

2023-03-20 16:04 UTC, alvls commented
Дарья, добавьте исходные коды в проекты. Сейчас в проектах task1, task2 пусто. Первую работу я принял так. Вторую не буду.

2023-03-23 12:30 UTC, alvls requested changes

2023-03-23 12:30 UTC, alvls commented on Ermilova_DS/task2/ConsoleApplication.cpp
> +	void Create_arr() {
У вас смешение стилей в именовании функций. Выберите один и используйте его везде.
Например, все имена строчными, между словами символ _.

2023-03-23 12:30 UTC, alvls commented on Ermilova_DS/task2/ConsoleApplication.cpp
> +			arr[i] = (rand() % 100);
Не нужно автоматически заполнять массив. Это должен делать пользователь класса.

2023-03-23 12:30 UTC, alvls commented on Ermilova_DS/task2/ConsoleApplication.cpp
> +		this->size = size;
При изменении размера нужно перевыделять память.

2023-03-23 12:30 UTC, alvls commented on Ermilova_DS/task2/ConsoleApplication.cpp
> +		return "\n";
В методах класса не д.б. ввода с консоли, только получение данных через параметры методов.

2023-03-23 12:30 UTC, alvls commented on Ermilova_DS/task2/ConsoleApplication.cpp
> +	string is_ordered() {
Нужно вернуть не строку, а значение типа bool

2023-03-23 12:30 UTC, alvls commented on Ermilova_DS/task2/ConsoleApplication.cpp
> +	void subarray() {
Подмассив нужно выделить в виде объекта типа dynamic_array, а не вывести на экран.
При этом из исходного массива не нужно ничего удалять.

2023-03-23 12:31 UTC, alvls commented
Дарья, сколько вам нужно времени на устранение замечаний?

2023-03-28 11:32 UTC, alvls commented
По заданию 3. Не считая ошибки с имени Translition, все остальное хорошо. Откуда узнали про контейнер map?

2023-03-29 07:32 UTC, alvls requested changes

2023-03-29 07:32 UTC, alvls commented on Ermilova_DS/task2/ConsoleApplication.cpp
> +
Удалите пустые строки

2023-03-29 07:32 UTC, alvls commented on Ermilova_DS/task2/ConsoleApplication.cpp
> +		this->size = size;
Вызовите resize

2023-03-29 07:32 UTC, alvls commented on Ermilova_DS/task2/ConsoleApplication.cpp
> +	}
Не должно быть ввода с консоли. Данные нужно передавать через параметры методов. Например, так
```
void input_index(int i, double value)
```

2023-03-29 07:33 UTC, alvls commented
По заданию 2 - стало лучше, но все еще не достаточно. Оставшиеся замечания выше.

2023-03-30 20:33 UTC, ermilovad commented
> По заданию 3. Не считая ошибки с имени Translition, все остальное хорошо. Откуда узнали про контейнер map?

Здравствуйте, ошибки исправила, про контейнер map узнала из видео на ютубе.

2023-03-31 06:18 UTC, alvls commented
По заданию 2 исправили не все.

| __Работа  принята__       |      |
| ------------------------- | ---- |
| __Ваш текущий балл:__     |      |
| Функциональность:         | 3,0  |
| Качество  проектирования: | 1,2  |
| Качество кода:            | 1,5  |
| Бонус:                    | 0,0  |
| Штраф:                    | 0,0  |
| __Итого:__                | 5,7  |

2023-03-31 06:19 UTC, alvls commented
По заданию 3

| __Работа  принята__       |      |
| ------------------------- | ---- |
| __Ваш текущий балл:__     |      |
| Функциональность:         | 4,0  |
| Качество  проектирования: | 2,0  |
| Качество кода:            | 2,0  |
| Бонус:                    | 0,0  |
| Штраф:                    | 0,0  |
| __Итого:__                | 8,0  |

2023-03-31 06:19 UTC, merged