Moiseev task 1
alvls/mp1-2023-1 pull request #2
Opened 2023-02-27 10:13 UTC by MoiseevArt

2023-03-14 06:45 UTC, alvls requested changes

2023-03-14 06:45 UTC, alvls commented on moiseev_av/task1/Source.cpp
> +		cout << "\n������� �����: " << hours << "h. " << minutes << "m. " << seconds << "s. \n\n" << endl;
Здесь и далее: в методах класса не должно быть работы с консолью (кроме одного по условию задачи). Данные должны поступать в методы через параметры. Нужно переделать.

2023-03-14 07:45 UTC, alvls commented
Артём, я не имел ввиду, что нельзя использовать cout. Функция printf точно так же работает с консолью ввода/вывода. Его не должно быть в методах класса.
Данные должны поступать в методы через параметры, результаты нужно возвращать из методов, а не выводить на экран.

2023-03-14 08:05 UTC, MoiseevArt commented
Но я не использую printf. У меня метод, который выводит информацию в консоль, называется: "print"

2023-03-14 08:15 UTC, alvls commented
> Но я не использую printf. У меня метод, который выводит информацию в консоль, называется: "print"

Ок, но дело не в названии функции. Попробую объяснить еще раз. Ваш текущий вариант класса подразумевает, что его можно использовать только с консолью ввода/вывода, поскольку прямо в методах класса происходит ввод и вывод данных. Получается, что класс нельзя использовать в программах, где консоли нет (системных или с графическим интерфейсом).
Переделайте методы так, чтобы данные поступали в методы через параметры, а результаты возвращались из методов.

2023-03-14 08:23 UTC, MoiseevArt commented
Сейчас исправлю

2023-03-14 10:29 UTC, alvls commented
Исправили не все, но на этот раз зачту.

| __Работа  принята__       |      |
| ------------------------- | ---- |
| __Ваш текущий балл:__     |      |
| Функциональность:         | 3,0  |
| Качество  проектирования: | 1,5  |
| Качество кода:            | 1,5  |
| Бонус:                    | 0,0  |
| Штраф:                    | 0,0  |
| __Итого:__                | 6,0  |

2023-03-20 16:32 UTC, alvls requested changes

2023-03-20 16:32 UTC, alvls commented on moiseev_av/task2/Source.cpp
> +	Matrix(int i, int j) : i(i), j(j) { //������: this->i = i;
Крайне неудачные имена для размеров. Традиционно i, j используют в качестве индексов. Переименуйте.

2023-03-20 17:50 UTC, alvls commented
По заданию 2


| __Работа  принята__       |      |
| ------------------------- | ---- |
| __Ваш текущий балл:__     |      |
| Функциональность:         | 3,0  |
| Качество  проектирования: | 1,5  |
| Качество кода:            | 1,5  |
| Бонус:                    | 0,0  |
| Штраф:                    | 0,0  |
| __Итого:__                | 6,0  |

2023-03-28 07:33 UTC, alvls commented
Артём, отличная реализация!

| __Работа  принята__       |      |
| ------------------------- | ---- |
| __Ваш текущий балл:__     |      |
| Функциональность:         | 4,0  |
| Качество  проектирования: | 2,0  |
| Качество кода:            | 2,0  |
| Бонус:                    | 0,2  |
| Штраф:                    | 0,0  |
| __Итого:__                | 8,2  |

2023-03-28 07:33 UTC, merged