Pull request Task 1 Polikanov
alvls/mp1-2023-1 pull request #5
Opened 2023-02-28 11:04 UTC by polikanovv

2023-03-14 07:34 UTC, alvls commented
По заданию 1

| __Работа  принята__       |      |
| ------------------------- | ---- |
| __Ваш текущий балл:__     |      |
| Функциональность:         | 3,0  |
| Качество  проектирования: | 1,5  |
| Качество кода:            | 1,5  |
| Бонус:                    | 0,0  |
| Штраф:                    | 0,0  |
| __Итого:__                | 6,0  |

2023-03-20 13:32 UTC, alvls requested changes

2023-03-20 13:32 UTC, alvls commented on polikanov_v/task2/Source.cpp
> +			cout << "Incorrect data" << endl;
1. Уберите весь вывод на консоль
2. Если событие с неверной датой или дубликат, просто ничего не делайте.

2023-03-20 13:32 UTC, alvls commented on polikanov_v/task2/Source.cpp
> +	string getDate(string name) {
Узнать дату - это не получить строку. Нужны год, месяц и день по-отдельности

2023-03-20 13:32 UTC, alvls commented on polikanov_v/task2/Source.cpp
> +	string calcDiff(string name, int day, int month, int year) {
См. комментарий выше

2023-03-21 12:20 UTC, alvls requested changes

2023-03-21 12:20 UTC, alvls commented on polikanov_v/task2/Source.cpp
> +				return date;
Здесь и далее не годится. Нужно вернуть числа, а не строки.

2023-03-21 12:30 UTC, polikanovv commented
Александр Владимирович, добрый день. Исправил функции на возврат массивов со значениями типа int. 
Подскажите, пожалуйста, как мне стоило мыслить, чтобы не ошибаться и сразу выбирать правильный тип данных возвращаемых функцией, например, массива (int или str)

2023-03-21 13:11 UTC, alvls commented
> Александр Владимирович, добрый день. Исправил функции на возврат массивов со значениями типа int. Подскажите, пожалуйста, как мне стоило мыслить, чтобы не ошибаться и сразу выбирать правильный тип данных возвращаемых функцией, например, массива (int или str)

Нужно представить, как кто-то (а это может быть как человек, так и другой объект/функция/код) будет пользоваться вашим классом. Допустим кто-то хочет "узнать дату выбранного события". Что имеется ввиду под "узнать"? Неверно считать, что это значит "увидеть", поскольку "клиентом" может быть какая-то функция, для которой данные нужны в виде удобном для обработки. Числа намного удобнее/эффективнее обрабытавать чем строки. 
Подробнее можем обсудить очно.

2023-03-21 13:14 UTC, alvls requested changes

2023-03-21 13:14 UTC, alvls commented on polikanov_v/task2/Source.cpp
> +				static int difference[3] = {diffDays, diffMonths, diffYears};
Стало лучше, однако использовать статические переменные для возврата результата - не слишком хорошая идея. Подумайте, как можно вернуть результат другим способом, не связываясь с указателями.

2023-03-21 15:18 UTC, polikanovv commented
Использовал array, соответственно, избавился от указателей. Насколько это правильное решение?

2023-03-21 15:22 UTC, alvls commented
> Использовал array, соответственно, избавился от указателей. Насколько это правильное решение?

Это один из возможных вариантов. Не лучший в общем, но подходящий в данном задании.

2023-03-21 15:24 UTC, alvls commented
| __Работа  принята__       |      |
| ------------------------- | ---- |
| __Ваш текущий балл:__     |      |
| Функциональность:         | 3,0  |
| Качество  проектирования: | 1,5  |
| Качество кода:            | 1,5  |
| Бонус:                    | 0,0  |
| Штраф:                    | 0,0  |
| __Итого:__                | 6,0  |

2023-03-21 15:28 UTC, merged