task 1 complete
alvls/mp1-2023-1 pull request #6
Opened 2023-02-28 21:03 UTC by korablev-vm

2023-03-14 07:40 UTC, alvls requested changes

2023-03-14 07:40 UTC, alvls commented on korablev_vm/task1/Source.cpp
> +		system("cls");
Очистка экрана - лишняя в этом методе.

2023-03-14 07:40 UTC, alvls commented on korablev_vm/task1/Source.cpp
> +			cout << "Ошибка! Деление на 0 невозможно." << endl;
Здесь и далее: в методах класса не должно быть работы с консолью (кроме одного по условию задачи). Данные должны поступать в методы через параметры, результаты нужно возвращать из методов. Нужно переделать.

2023-03-14 13:19 UTC, korablev-vm commented on korablev_vm/task1/Source.cpp
> +			cout << "Ошибка! Деление на 0 невозможно." << endl;
Переделал с учетом всех исправлений

2023-03-14 13:38 UTC, alvls commented
| __Работа  принята__       |      |
| ------------------------- | ---- |
| __Ваш текущий балл:__     |      |
| Функциональность:         | 3,0  |
| Качество  проектирования: | 1,5  |
| Качество кода:            | 1,5  |
| Бонус:                    | 0,2  |
| Штраф:                    | 0,0  |
| __Итого:__                | 6,2  |

2023-03-20 13:44 UTC, alvls commented
По заданию 2

В целом все хорошо. Есть один замечание - название метода get_answ неудачное. Это получение не ответа, а коэффициента. Тем не менее

| __Работа  принята__       |      |
| ------------------------- | ---- |
| __Ваш текущий балл:__     |      |
| Функциональность:         | 3,0  |
| Качество  проектирования: | 1,5  |
| Качество кода:            | 1,5  |
| Бонус:                    | 0,0  |
| Штраф:                    | 0,0  |
| __Итого:__                | 6,0  |

2023-03-28 07:51 UTC, alvls requested changes

2023-03-28 07:51 UTC, alvls commented on korablev_vm/task3/Source.cpp
> +		}
Можно обойтись без такого длинного switch-a. Желательно исправить.

2023-03-28 07:51 UTC, alvls commented on korablev_vm/task3/Source.cpp
> +			cout << "Квадратный корень берется только от неотрицательных чисел" << endl;
Условие записано неудачно. Если ввести левую границу 0, срабатывает. А не должно.

2023-03-28 08:48 UTC, korablev-vm commented on korablev_vm/task3/Source.cpp
> +			cout << "Квадратный корень берется только от неотрицательных чисел" << endl;
Добрый день. Длинный switch заменил. Для корня переписан метод получения пределов. 0 для левого оставлен как крайняя граница, при нем все хорошо считается. Значения меньше отметаются.

2023-03-28 09:10 UTC, alvls commented
По заданию 3

| __Работа  принята__       |      |
| ------------------------- | ---- |
| __Ваш текущий балл:__     |      |
| Функциональность:         | 4,0  |
| Качество  проектирования: | 2,0  |
| Качество кода:            | 2,0  |
| Бонус:                    | 0,0  |
| Штраф:                    | 0,0  |
| __Итого:__                | 8,0  |

2023-04-07 06:35 UTC, alvls commented
Отличная работа!

| __Работа принята__        |      |
| ------------------------- | ---- |
| __Ваш текущий  балл:__    |      |
| Функциональность:         | 4,0  |
| Качество  проектирования: | 2,0  |
| Качество  кода:           | 2,0  |
| Бонус:                    | 0,2  |
| Штраф:                    | 0,0  |
| __Итого:__                | 8,2  |

2023-04-07 06:37 UTC, merged