task 1 Васильев С.А
alvls/mp1-2023-1 pull request #8
Opened 2023-03-01 09:58 UTC by venn2713

Здравствуйте. Можете объяснить что именно нужно реализовать в классе? Я понял это как то, что при создании объекта класса будут указывать long long int, а сам класс уже должен хранить это число используя unsigned int, тоесть мы по сути должны разбить большое число на блоки и посчитать количество полностью заполненных и сохранить их где-то, а также один остаток. Ну и знак. Но при всем при этом надо реализовать то, что если в ходе сложения или вычетания мы выйдем за границы long long int, то должна сработать семантика как для знаковых. Я  правильно понял задачу?

2023-03-14 08:06 UTC, alvls commented
Сергей, почему-то гитхаб не прислал мне ваш вопрос от 1 марта.
Я посмотрел реализованный вами вариант по заданию 1 - вы все сделали правильно.

| __Работа  принята__       |      |
| ------------------------- | ---- |
| __Ваш текущий балл:__     |      |
| Функциональность:         | 3,0  |
| Качество  проектирования: | 1,5  |
| Качество кода:            | 1,5  |
| Бонус:                    | 0,3  |
| Штраф:                    | 0,0  |
| __Итого:__                | 6,3  |

2023-03-20 14:13 UTC, alvls commented
Сергей, вы написали неплохой код по заданию 2, хоть и с некоторыми ошибками. Но дело в том, что ваш код не соответствует заданию. Сбило с толку, видимо, то, что в класс динамический массив в std называется vector, но им не является )). А в задании требовалось, если вы внимательно прочтете задание, разработать класс Вектор, соответствующий понятию из линейной алгебры. Нужно переделать.

2023-03-20 14:19 UTC, venn2713 commented
Аааа... А я что-то и не подумал...
Хорошо, я завтра, в крайнем случае послезавтра, скину решение для векторов из линейной алгебры))

2023-03-23 13:40 UTC, venn2713 commented
Здравствуйте, у меня есть вопрос. Если у меня в классе, например в конструкторе, выделена память под массив, то могу ли я потом не удаляя эту память просто снова вызвать new и "перезаписать" его?

2023-03-23 13:52 UTC, alvls commented
> Здравствуйте, у меня есть вопрос. Если у меня в классе, например в конструкторе, выделена память под массив, то могу ли я потом не удаляя эту память просто снова вызвать new и "перезаписать" его?

Нет, без удаления обойтись не удастся.

2023-03-23 13:52 UTC, venn2713 commented
Тоесть я сперва удаляю, а потом снова создаю сразу?

2023-03-23 13:55 UTC, alvls commented
> Тоесть я сперва удаляю, а потом снова создаю сразу?

А вот тут зависит от сценария: надо ли копировать данные, например.

2023-03-23 13:57 UTC, venn2713 commented
Тут если я пересоздаю имеющийся, то только чтобы скопировать в него данные из другого, так что видимо могу удалять

2023-03-23 14:12 UTC, venn2713 commented
У меня рушится программа, если я сперва удаляю, но при использовании просто new всё копируется правильно
Я просто перегружаю операнд = для векторов, и вот там я проверяю на уже созданном векторе, присваивая ему значения.
Работающая версия:
	Vector& operator = (const Vector another)
	{
		size = another.size;
		arr = new int[size];
		for (int i = 0; i < size; i++)
			arr[i] = another.arr[i];
		return *this;
	}
Не то что бы работающая:
	Vector& operator = (const Vector another)
	{
		size = another.size;
		delete[] arr;
		arr = new int[size];
		for (int i = 0; i < size; i++)
			arr[i] = another.arr[i];
		return *this;
	}
Видимо я не так удалил?

2023-03-23 14:28 UTC, alvls commented
> У меня рушится программа, если я сперва удаляю, но при использовании просто new всё копируется правильно...

Если к моменту вызова delete у вас память а) была выделена, б) не была удалена, то второй код должен работать.

2023-03-23 14:30 UTC, venn2713 commented
Но вот почему-то не работает... Возможно что деструктор срабатывает первее?

2023-03-23 14:34 UTC, alvls commented
> Но вот почему-то не работает... Возможно что деструктор срабатывает первее?

Пока не увижу весь код, не могу сказать.

2023-03-23 14:34 UTC, venn2713 commented
Сейчас отправлю тогда как рабоатет

2023-03-23 14:40 UTC, alvls commented
Закоммитили только файл с проектом task3

2023-03-23 16:12 UTC, venn2713 commented
Не то скинул, торопился

2023-03-23 17:19 UTC, alvls requested changes

2023-03-23 17:19 UTC, alvls commented on vasilev_sa/task2/Source.cpp
> +	Vector& operator = (const Vector another)
1. ссылку забыли
2. добавьте удаление (у меня с ним работает)

2023-03-24 16:16 UTC, alvls commented
Теперь похоже на то, что было нужно. В этот раз снижать баллы за задержку не буду. В дальнейшем постарайтесь внимательнее читать задание)).

| __Работа  принята__       |      |
| ------------------------- | ---- |
| __Ваш текущий балл:__     |      |
| Функциональность:         | 3,0  |
| Качество  проектирования: | 1,5  |
| Качество кода:            | 1,5  |
| Бонус:                    | 0,2  |
| Штраф:                    | 0,0  |
| __Итого:__                | 6,2  |

2023-03-28 07:54 UTC, alvls commented
По заданию 3 - в проекте нет ничего, кроме файла console.h. Исправьте.

2023-03-28 07:57 UTC, venn2713 commented
Сейчас сделаю, у меня в папке... Странно

2023-03-28 08:08 UTC, alvls commented
Ничего не изменилось. Вот так выглядит проект в студии
![изображение](https://user-images.githubusercontent.com/5449780/228171008-7329cd82-fde8-4976-bf11-1d7367af54f0.png)

2023-03-28 10:59 UTC, venn2713 commented
![image](https://user-images.githubusercontent.com/112872559/228215347-104068f7-31ff-4c67-aa48-334ec12f85b6.png)
А что мне сделать тогда?

2023-03-28 11:00 UTC, venn2713 commented
![image](https://user-images.githubusercontent.com/112872559/228215535-1582750e-72a1-4900-bb56-c63a1bb761a9.png)
У меня даже тут он отображается

2023-03-28 11:28 UTC, alvls commented
Теперь появилось два файла с одинаковым содержимым и без функции main

2023-03-28 15:29 UTC, alvls commented
main появилась, но два файла с двумя классами по имени Menu так и остались. Исправьте.

2023-03-29 07:13 UTC, alvls commented
Сергей, ёлки-моталки, исправьте по-нормальному. Состояние проекта в студии, файлов в каталоге проекта и файлов на гитхабе должно быть согласованно. А у вас при каждом очередном коммите в одном из этих трех мест что-то не так.

2023-03-29 07:17 UTC, venn2713 commented
Видимо мне нужна помощь, я уже всё пытался сделать, просто я на компьютере удалил один из файлов через студию, он исчез, а потом я отправил коммит и вы сказали ничего не поменялось, а у меня уже нет файла, ни в студии ни на компьютере. Ну и потом я стер файл с гитхаба… но видимо опять чтото не то 😅

2023-03-29 07:34 UTC, alvls commented
> Видимо мне нужна помощь, я уже всё пытался сделать, просто я на компьютере удалил один из файлов через студию, он исчез, а потом я отправил коммит и вы сказали ничего не поменялось, а у меня уже нет файла, ни в студии ни на компьютере. Ну и потом я стер файл с гитхаба… но видимо опять чтото не то 😅

В четверг после пары покажу очно, что и как нужно сделать.

2023-03-30 11:19 UTC, venn2713 commented
Здравствуйте, плохо чувствовал себя сегодня, не смог приехать, может есть какая-то инструкция как я могу сам сделать?

2023-03-30 12:11 UTC, alvls commented
> Здравствуйте, плохо чувствовал себя сегодня, не смог приехать, может есть какая-то инструкция как я могу сам сделать?

1. Откройте в каком-нибудь редакторе файл task3.vcxproj. Удалите в нем строки (целиком), в которых есть Source2.cpp.
2. Переименуйте в папке проекта task3 файл Source2.cpp в Source.cpp
3. Откройте проект task3 в студии и убедитесь, что 
- в проекте есть файлы console.h и Source.cpp
- нет других файлов
- оба файла открываются
4. Сделайте коммит и пуш на гитхаб.

2023-03-30 19:29 UTC, alvls requested changes

2023-03-30 19:29 UTC, alvls commented on vasilev_sa/task3/Source.cpp
> +	}
Код метода не согласован с его назначением. Да и нужен ли он?

2023-03-30 19:29 UTC, alvls commented on vasilev_sa/task3/Source.cpp
> +	void Print(int x = 0, int y = 0)
Сценарий использования класса Меню не продуман, поэтому реализация неверная.

2023-03-30 19:31 UTC, alvls commented
По заданию 3 вы исчерпали лимит времени. Дальше пойдет штраф за просрочку. Тем не менее, правки нужно внести.

2023-04-01 09:33 UTC, alvls commented
Теперь меню, по крайней мере, можно пользоваться. Был более простой вариант - назвать метод Print "Choice" и вернуть из него номер выбранного пункта.

| __Работа  принята__       |      |
| ------------------------- | ---- |
| __Ваш текущий балл:__     |      |
| Функциональность:         | 4,0  |
| Качество  проектирования: | 2,0  |
| Качество кода:            | 2,0  |
| Бонус:                    | 0,0  |
| Штраф:                    | 0,5  |
| __Итого:__                | 7,5  |

2023-04-07 06:44 UTC, alvls commented
По заданию 4 все отлично! Есть только один комментарий - реализацию метода songList можно написать гораздо короче)).

| __Работа принята__        |      |
| ------------------------- | ---- |
| __Ваш текущий  балл:__    |      |
| Функциональность:         | 4,0  |
| Качество  проектирования: | 2,0  |
| Качество  кода:           | 2,0  |
| Бонус:                    | 0,3  |
| Штраф:                    | 0,0  |
| __Итого:__                | 8,3  |

2023-04-10 09:37 UTC, merged