Task 1.3, Шведова
alvls/mp1-2023-1 pull request #9
Opened 2023-03-01 13:41 UTC by shvedovav

2023-03-14 08:47 UTC, alvls commented
Виталина, ваш текущий вариант класса подразумевает, что его можно использовать только с консолью ввода/вывода, поскольку прямо в методах класса происходит ввод и вывод данных. Получается, что класс нельзя использовать в программах, где консоли нет (системных или с графическим интерфейсом).
Переделайте методы так, чтобы данные поступали в методы через параметры, а результаты возвращались из методов.
Оставить для вывода нужно только метод PrintTime.

2023-03-14 10:38 UTC, alvls commented
Теперь все верно.


| __Работа  принята__       |      |
| ------------------------- | ---- |
| __Ваш текущий балл:__     |      |
| Функциональность:         | 3,0  |
| Качество  проектирования: | 1,5  |
| Качество кода:            | 1,5  |
| Бонус:                    | 0,0  |
| Штраф:                    | 0,0  |
| __Итого:__                | 6,0  |

2023-03-20 14:49 UTC, alvls requested changes

2023-03-20 14:49 UTC, alvls commented on shvedova_va/task2/Source.cpp
> +	}
Нужно вернуть результат, а не менять левый операнд.

2023-03-20 14:49 UTC, alvls commented on shvedova_va/task2/Source.cpp
> +	 void AskElement(int i, int j, int n)
Лучше назвать SetElement

2023-03-20 14:49 UTC, alvls commented on shvedova_va/task2/Source.cpp
> +	Matrix(Matrix& MM)
Лучше так Matrix(const Matrix& MM)

2023-03-23 09:29 UTC, shvedovav commented
Александр Владимирович, не отображается почему-то Ваш последний комментарий с новыми исправлениями. Не могли бы Вы его продублировать?

2023-03-23 09:53 UTC, alvls requested changes

2023-03-23 09:53 UTC, alvls commented on shvedova_va/task2/Source.cpp
> +	void SumMatrix(const Matrix& m1, const Matrix& m2)
Все еще неверно. Прототип д.б. таким
```
Matrix SumMatrix(const Matrix& m);
```
Вспомните сложение комплексных чисел.

2023-03-23 09:53 UTC, alvls commented
> Александр Владимирович, не отображается почему-то Ваш последний комментарий с новыми исправлениями. Не могли бы Вы его продублировать?

А теперь?

2023-03-23 10:07 UTC, shvedovav commented
Да, вижу, спасибо. Все исправлю

2023-03-23 19:24 UTC, shvedovav commented
Реализовала сумму матриц в соответствии с прототипом, надеюсь, это то, что нужно.

2023-03-24 10:03 UTC, alvls commented
| __Работа  принята__       |      |
| ------------------------- | ---- |
| __Ваш текущий балл:__     |      |
| Функциональность:         | 3,0  |
| Качество  проектирования: | 1,5  |
| Качество кода:            | 1,5  |
| Бонус:                    | 0,0  |
| Штраф:                    | 0,0  |
| __Итого:__                | 6,0  |

2023-03-28 08:04 UTC, alvls commented
По заданию 3

| __Работа  принята__       |      |
| ------------------------- | ---- |
| __Ваш текущий балл:__     |      |
| Функциональность:         | 4,0  |
| Качество  проектирования: | 2,0  |
| Качество кода:            | 2,0  |
| Бонус:                    | 0,0  |
| Штраф:                    | 0,0  |
| __Итого:__                | 8,0  |

2023-03-28 08:05 UTC, merged